### ISSUE TITLE
Possibility of specifying more complicated row effect structures

### ISSUE THREAD

**Issue by RodolfoPelinson** [JenniNiku/gllvm#1]
Hi. I was wondering if the package provides any alternatives of specifying more complicated row effect structures beyond a single row effect unique to each row. For example, specifying row IDs. I have community data sampled in the same locations at multiple times. I would like to fit one single gllvm for all of the observations, but accounting for this "repeated measures" design. Is there any way to do that in the current version of the package?

Thank you.

**Comment by JenniNiku** [comment]
Currently only structure available for row effects is a single row effect unique to each row.

**Comment by JenniNiku** [comment]
There is now a possibility to define structure for random row effects. This can be done by specifying the structure via formula in row.eff argument. For example row.eff = ~(1|group) gives row effects for each group, not for each row. Additionally, correlation structure between groups can be defined, row.eff = ~corCS(1|group), when compound symmetry structure is set for row parameters. Alternative correlation structures are corAR1 and corExp. If there is same number of observational units in each group, the correlation structure can be set for site effects of the observational units within group. I try to add examples to the documentation soon.

**Comment by hrlai** [comment]
Thanks for such a handy R package! I'd like to ask about the possibility of more complicated _column_ effect structures, now that some row-effect structures have been implemented. (Rather than open a new thread I chose to continue the inquiry here, to minimise new thread, hope this is fine.)

As you're probably well aware, a commonly requested column effect structure is to incorporate species phylogeny, _ala_ the **C**  matrix in [Ovaskainen et al. 2017](https://onlinelibrary.wiley.com/doi/10.1111/ele.12757). Is it possible to implement this to induce correlation for the beta parameters?

Thanks in advance.

**Comment by JenniNiku** [comment]
Hi. Incorporating species phylogeny is not in our plans in the near future, unfortunately. I will see later if it would be possible to implement that in longer term.

**Comment by hrlai** [comment]
Ah, I see, thanks for the heads-up and I look forward to see if species phylogeny is possible or in-line with the `gllvm` philosophy.

**Comment by BertvanderVeen** [comment]
> Thanks for such a handy R package! I'd like to ask about the possibility of more complicated _column_ effect structures, now that some row-effect structures have been implemented. (Rather than open a new thread I chose to continue the inquiry here, to minimise new thread, hope this is fine.)
> 
> As you're probably well aware, a commonly requested column effect structure is to incorporate species phylogeny, _ala_ the **C** matrix in [Ovaskainen et al. 2017](https://onlinelibrary.wiley.com/doi/10.1111/ele.12757). Is it possible to implement this to induce correlation for the beta parameters?
> 
> Thanks in advance.

A bit late, but I am working on implementing this now, did you have any special requests for this?
