### ISSUE TITLE
gllvm crashes with tweedie

### ISSUE THREAD

**Issue by BertvanderVeen** [JenniNiku/gllvm#102]
The following example crashes gllvm:

```
data("microbialdata")
dat<-exp(microbialdata$Y)
mod<-gllvm(dat,num.lv=2,family="tweedie")
```

**Comment by BertvanderVeen** [comment]
Should probably add defense programming to check for NA in the predictors, and throw a error if there are any.

**Comment by smithja16** [comment]
I also get an error with a tweedie and trying to fit quadratic terms in formula (x + x2) - "error in optim... L-BFGS-B need finite values of 'fn'". Model works with gaussian.

**Comment by smithja16** [comment]
Thanks, I'll try that. If I have further Qs I'll post in Discussions.
