### ISSUE TITLE
Points' colors meaning in residuals vs linear predictors

### ISSUE THREAD

**Issue by zohrazahir** [JenniNiku/gllvm#121]
Hello, 

### I am wondering if anyone knows what colors in the residuals vs linear predictor plot signify.

Here is the code for plotting: 

```
par(mfrow = c(1, 2))
plot(fit_gllvm, which = 1:2, n.plot = 100)
```

### When I add var.colors to the above code, it changes all the points to one color (for example, color 7, which is yellow) 

```

par(mfrow = c(1, 2))
plot(fit_gllvm, which = 1:2, n.plot = 100, var.colors = 7)
```
![without var colors](https://github.com/JenniNiku/gllvm/assets/72106136/f9405fa7-5815-4103-a79a-5c306349c158)
![with var colors](https://github.com/JenniNiku/gllvm/assets/72106136/298df8b0-e44b-42f1-b406-88e4c1710166)

Also, can you help me interpret the below graph? (It shows the residuals vs linear predictor based on Poisson and negative binomial: 

 
![Poisson vs NB](https://github.com/JenniNiku/gllvm/assets/72106136/9f5336d3-773b-4b39-8648-7a9344109e07)

Thank you,
Z.

**Comment by BertvanderVeen** [comment]
Thanks. I will respond to your question, but in the discussion forum as this is not a bug :)
