### ISSUE TITLE
error with predict.region = TRUE

### ISSUE THREAD

**Issue by AlainZuur** [JenniNiku/gllvm#166]
Development version. Runs fine without the prediction.region. Ran ok in the CRAN version. 

> ordiplot(M4,
+          biplot = TRUE,
+          s.cex = 0.4,
+          s.colors = grey(0.5),
+          cex.env = 0.9,
+          predict.region = TRUE,
+          col.ellips = "green")
Error in Q[(1:n) + n * (q - 1) + radidx, which(names(fit$TMBfn$par[fit$Hess$incl]) ==  : 
  incorrect number of subscripts on matrix

M4 is a GLLVM with 2 constrained latent variables.

No hurries! It is not a thing I use often.

Alain

**Comment by BertvanderVeen** [comment]
Addressed and solved. Thanks for reporting; caused by one of my recent changes as well.
