### ISSUE TITLE
randomCoefplot

### ISSUE THREAD

**Issue by AlainZuur** [JenniNiku/gllvm#171]
Sorry to keep you busy on a Saturday.

This is from the help file of randomCoefplot.gllvm. If I run this code, then it crashes R. From a fresh restart. Multiple times.
I don't think it did that for the CRAN version.

The reason that I ran the demo code is that randomCoefplot didn't want to give me SEs anymore. CRAN did.

Alain

library(gllvm)

data(antTraits)
y <- as.matrix(antTraits$abund)
X <- as.matrix(antTraits$env)
TR <- antTraits$traits
# Fit model with random slopes
fitF <- gllvm(y = y, X = X, TR = TR,
 formula = ~ Bare.ground + Bare.ground : Webers.length,
 family = poisson(), randomX = ~ Bare.ground)
randomCoefplot(fitF)

**Comment by BertvanderVeen** [comment]
Ok, I will take a look.

**Comment by BertvanderVeen** [comment]
Oof, that took me a while. Found the bug, fixed it.

**Comment by BertvanderVeen** [comment]
@AlainZuur can you confirm that this is solved?
