### ISSUE TITLE
Control options in gllvm()?

### ISSUE THREAD

**Issue by BertvanderVeen** [JenniNiku/gllvm#18]
There are a lot of configuration options in `gllvm() ` now. Could it be interesting to summarize these in a bunch of control statements, similar to in `boral`, `lme4 `or `glmmTMB`? E.g. in the format of:

`gllvm(y, num.lv=2, family="poisson", sd.errors=T, control =list(options), control.start = list(options), control.traits =list(options), control.rows=list(options)) `

This will make it easier for users of the package to find what they are searching for, due to a basic classification providing a better overview of all possibilities, organize the documentation a bit, and allow future inclusion of the quadratic `gllvm `in the form of  `control.quadratic = list(options)` (though there are various ways to do the latter, can also be in a separate function).

**Comment by JenniNiku** [comment]
Yes, I agree, I have been thinking that too. It starts to look bit messy with that many control params. At least the starting value options, and contol params for optimization are most obvious. I put this high on my TODO list.

**Comment by BertvanderVeen** [comment]
Great! Feel free to drop me a message if I can be of assistance.
