### ISSUE TITLE
Gamma GLLVM: argument "shape" is missing

### ISSUE THREAD

**Issue by AlainZuur** [JenniNiku/gllvm#180]
Got an error with the development version. Works ok in CRAN version.
Alain

M1.X <- gllvm(y = MorphData, 
              X = CovData,
              formula = ~ Location,
              row.eff = "random",
              num.lv = 1, 
              seed = 12345,
              control.start = list(n.init = 5, jitter.var = 0.1),
              family = "gamma")

Error in pgamma(as.vector(y)) : 
  argument "shape" is missing, with no default

**Comment by BertvanderVeen** [comment]
Thanks Alain, this was a bug caused by a change in the development version, and has now been fixed.

**Comment by AlainZuur** [comment]
Thanks. I am rerunning all exercises from scratch again..using the development version. I have a few more errors popping up. But will send them tonight or tomorrow. 

Alain

**Comment by BertvanderVeen** [comment]
Sounds good. I am very busy this week but I am happy to address them as soon as I can.
