### ISSUE TITLE
Covariates for row effects

### ISSUE THREAD

**Issue by BertvanderVeen** [JenniNiku/gllvm#184]
Wishlist: allow `row.eff` to also include covariates (with/without random slopes?) for which effects are assumed to be the same for all species. This allows to fit models that answer questions both with respect to the total abundance or richness at a site, as well as for species/communities. E.g.,:

`
gllvm(y, X, row.eff = ~elevation + (1|area), formula = ~ shrubs, num.lv = 2)
`

**Comment by gerverska** [comment]
Hi Bert! This sounds like are really interesting enhancement (I think I have a perfect use case for it). Do you see this feature hitting the dev version anytime soon? All good if not--just curious.

**Comment by BertvanderVeen** [comment]
I have not worked on this (yet), and do not have the possibility to do so in the next half a year, earliest January. The implementation is relatively trivial, so it should be quick to implement.

**Comment by BertvanderVeen** [comment]
See #195. I am happy for someone to try that out and potentially help me spot bugs.

**Comment by gerverska** [comment]
Sorry about the delay on this! I'm a bit in writing world right now, but I
can give this a try sometime soon.

Thanks for following up, Bert!

**Comment by BertvanderVeen** [comment]
Now merged into the main branch.
