### ISSUE TITLE
Multple random intercepts: R session aborts

### ISSUE THREAD

**Issue by SethMusker** [JenniNiku/gllvm#198]
Using example code from #16 my R session aborts (tested on two computers with different R versions (4.4.1 and 4.3.0).

![sessionAbort_gllvm](https://github.com/user-attachments/assets/f5d73049-19ea-4c19-a59c-a84329915af9)

```r
packageVersion("gllvm")
[1] ‘1.4.8’
```

github version installed with `pak::pak("JenniNiku/gllvm")`

EDIT: this actually only happens with the nested random effect.

**Comment by BertvanderVeen** [comment]
Thanks for another excellent report, this has been addressed.
