### ISSUE TITLE
Error in t.default(cbind(fit.mva$params$beta0, fit.mva$params$Xcoef)) : argument is not a matrix

### ISSUE THREAD

**Issue by ibrila** [JenniNiku/gllvm#21]
Hi!

I'm trying to use gllvm to look at differences in species composition of the gut microbiome. I have fit the null model using negative binomial distribution and using 3 latent variables. I then moved on (tried to) to fit the full model (80 samples, 20 variables), and then I want to move on to model selection using MuMIn.

Full model:

gllvm(y=otus_metals, X=gllvm_meta_upd, family = "negative.binomial", num.lv = 3, row.eff = TRUE)`

When I'm trying to fit the full model, I get the following errors:

Error 1:

```
"Error in t.default(cbind(fit.mva$params$beta0, fit.mva$params$Xcoef)) : argument is not a matrix"
```
Since the null model run without any problems, I figured the issue is with the covariate data frame. The structure of the data frame:

```
str(gllvm_meta_upd)
'data.frame':	80 obs. of  20 variables:
 $ BCI       : num  0.61 -1.007 1.228 0.552 2.131 ...
 $ head_w    : num  12.2 12.5 13.1 13.6 12.9 ...
 $ sex       : Factor w/ 2 levels "female","male": 2 1 1 1 1 2 1 2 1 2 ...
 $ location  : Factor w/ 2 levels "Location.1","Location.2": 2 2 2 2 1 2 2 1 2 2 ...
 $ study_area: Factor w/ 7 levels "Area.1","Area.2",..: 7 7 7 7 2 7 7 2 6 6 ...
 $ As        : num  -2.22 -2.27 -1.99 -2.41 -1.45 ...
 $ Cd        : num  0.0239 0.065 0.6333 0.2192 1.1256 ...
 $ Co        : num  -0.906 -0.894 -0.565 -0.605 -0.285 ...
 $ Cr        : num  -1.25 -1.1 -1.18 -1.57 -1.66 ...
 $ Cu        : num  1.31 1.34 1.24 1.25 1.22 ...
 $ Fe        : num  3.1 2.58 2.33 2.52 2.43 ...
 $ Hg        : num  -1.0347 -0.639 0.0359 -0.9443 -0.4534 ...
 $ Mn        : num  0.513 0.519 0.706 0.559 0.733 ...
 $ Mo        : num  0.3191 0.3271 0.2222 0.1904 -0.0997 ...
 $ Ni        : num  -0.971 -0.868 -0.901 -1.064 -0.652 ...
 $ Os        : num  -3.58 -3.59 -3.46 -3.95 -5.02 ...
 $ Pb        : num  0.594 0.221 0.8 0.555 0.363 ...
 $ Se        : num  0.39 0.472 0.425 0.476 0.627 ...
 $ V         : num  -2.61 -2.45 -2.47 -3.01 -2.76 ...
 $ Zn        : num  1.96 1.94 2.04 1.98 2.04 ...
```
 
If I run some of the variables in the full model, it starts working without any errors. As soon as I want to use the full model, it doesn't work. I've tried various options e.g. transforming data frame to a matrix (problem there is that it makes everything into characters and the full model gives "unexpected numeric constant" error), including and excluding the sampleIDs as row names. Nothing seems to work. I'm not a very experienced R user, so very little idea about where the problem might be (data frame, model formulation, R or gllvm)
 
Error 2:

```
In addition: Warning message:
In gllvm.TMB(y = y, X = X, family = family, num.lv = 0, starting.val = "zero",  :
  Error in nlminb(objr$par, objr$fn, objr$gr, control = list(rel.tol = reltol,  : 
  long vectors not supported yet: memory.c:3717
```
  
The issue persists on 2 versions of R, I'm checking it on a laptop with R 4.0.2 and then trying to run it through CSC's supercomputer Puhti with R 3.6.3.

**Comment by BertvanderVeen** [comment]
Hello! Nice that you're interested in using the package. 

In my experience, the first error has to do with generation of starting values, which for some reason is not going according to plan. Is your response a count?

I've encountered the second error before, though I'm afraid I'm not completely sure why it occurs.

**Comment by BertvanderVeen** [comment]
Hello! Nice that you're interested in using the package. 

In my experience, the first error has to do with generation of starting values (so probably not your data frame for X), which for some reason is not going according to plan. Some things to consider: is your response a count (as required for the negative-binomial distribution)? Have you tried running your model with `starting.val="zero"`? Have you ruled out any colinearity in your predictors?

Do note that the above model contains in the vicinity of `20*2 + 20*17+20*6+20*3-3+80 = 637` parameters (p = 20, p for the intercepts and again for the overdispersion parameters, p*17 for continuous predictors, p*6 for study_area, p*2 for the other two factors, p*num.lv-num.lv for the latent variables, 80 for the OTUintercepts. If your data is heavy in zeros (as suggested by the negative-binomial distribution), there might not be enough information to estimate all of those parameters.

**Comment by ibrila** [comment]
Hi,

I'm basically following the "Analysing high-dimensional microbial community data using gllvm" vignette. My response variable is an otu_table of 2705 otu(species) counts in 80 samples. 
I just tried adding `starting.val="zero"`, and got this as an output:
```
Warning messages:
1: In gllvm.TMB(y, X = X, formula = formula, num.lv = num.lv, family = family,  :
  Error : cannot allocate vector of size 599 Kb

2: In gllvm(y = otus_metals, X = data.frame(gllvm_meta_upd), family = "negative.binomial",  :
  Algorithm converged to infinity, try other starting values or different method.
```
I have looked at collinearity, and everything is looking good.

I tried removing one of the variables (study.area) from full model, and it seems to be running. I used it as a random factor in other analyses (to account for pseudo-replication), but it seems like it's still not included in gllvm  yet (I noticed that you're working on the issue).

So it might be that there's simply to many variables and model fails because of that?

**Comment by BertvanderVeen** [comment]
Right! Then I misunderstood. In that case, the number of parameters is more in the vicinity of `2705 *2 + 2705 *17 + 2705 *6 + 2705 *2 + 2705 *3 - 3 + 80 = 81227` with `2+17+6+2+3` or so per species. So, depending on how many zeros you actually have in your data, I do think that's on the heavy side.

A good start to toning down the number of parameters is by looking for colinearity in your predictors, and trying to prioritize. If that's not an option, try to determine which predictors you are most interested in and start with that. You can also try to find the fall-off point for the number of predictors, by starting low and adding more each time (if you don't mind a long process..). 

Do note, that support for the `dredge(.)` function is (I think) not on CRAN yet, so you might have to install the development version of the package with `devtools::install_github("JenniNiku/gllvm")`.

**Comment by ibrila** [comment]
Yeah, it's quite the dataset to analyze. 

I was kind of hoping to do that with the help of dredge, because in this instance, this is the already scaled-down version of the model, although I might need to just rip the bandaid off and drop something. There are a lot of OTUS that are not present in some study areas, but then that also describes the community composition, so just the sampling site might account for a lot of the differences seen in composition, so it's also a bit weird to exclude it. 

Thanks for the heads up about dredge, might have forgotten that it's not there!

**Comment by BertvanderVeen** [comment]
You could consider grouping some of the study areas, if that's defendable by their similarity. I agree that the row intercepts might have with some of the variation of study areas. 

Do note, dredge can take a while as it fits all subsets of the model by default. Also, you will have to refit the final model to get the results.

Let me know if you have any other difficulties, happy to help making it work.

**Comment by ibrila** [comment]
The problem with grouping would be that then it could be reflecting same information as location or another variable not included in this model.

Another question I've thinking about is the row.effects parameter. In the vignette it says that it's included 
>in order to account for the differences in site totals

but if the dataset I use has been rarefied, as is common in microbiome analysis, then all the samples have the same total, thus row.effects should potentially be set to FALSE?

**Comment by BertvanderVeen** [comment]
I'm not very familiar with the concept of rarefaction, but if the sites totals are the same you can exclude the row effect.

**Comment by ibrila** [comment]
Hi,

Given that I'm a newbie in stats, I was wondering what are your thoughts on the idea of basing inclusion of variables on the correlation between OTUs(collapsed to genus level for obvious reasons) and variables OR based on Mantel test results between Bray-Curtis distance matrix and individual variable Euclidian distance matrix?
Or am I grossly overthinking it/ misunderstanding something? I know that gllvm itself isn't based on distance matrices, but maybe that could help to make a somewhat informed decision about which variables to include?

**Comment by BertvanderVeen** [comment]
If your model runs fine without the study area variable, my suggestion is to feed the model to the dredge function and let it do it's magic.

If not, examine your data, find out which variable is causing issues and for what reason. You could do a manual selection, where you start with models including single predictors, and build from there, to get an impression of which predictors explain most variation in your community.

As I understand it, with the distance matrices you would be considering what explains the dissimilarity between your samples most, not what drives your OTUs, so I wouldn't recommend that.

**Comment by ibrila** [comment]
Thanks for your reply! I think I will stick to the full model and then see what shows up. I do have a hypothesis about what might be driving the differences, but some previous results have shown quite interesting influences, so I don't want to leave any stone unturned.

Great point about the distance matrices! Thanks for all the help!
