### ISSUE TITLE
Calculation of explained variation for negative binomial model

### ISSUE THREAD

**Issue by KwnLi** [JenniNiku/gllvm#25]
Hello @JenniNiku , in your [vignette1 document](https://cran.r-project.org/web/packages/gllvm/vignettes/vignette1.html), you provide an example on how to calculate the variation explained by the environmental variables with the ratio of the traces from the residual covariance matrices of the null and environmental models:

    rcov <- getResidualCov(fit_env, adjust = 0)
    rcov0 <- getResidualCov(fit3lv, adjust = 0)
    rcov0$trace; rcov$trace
    #> [1] 71.63626
    #> [1] 53.42926
    1 - rcov$trace / rcov0$trace
    #> [1] 0.254159

In your example, the fitted models have negative binomial distributed responses. Why is the `adjust` argument set then to 0 in this case? From the documentation I read `adjust` should be 1 or 2 for negative binomial. Or is it not necessary in this application?

Thanks a lot,
Kevin

**Comment by JenniNiku** [comment]
Hi,

Thank you for the question.
This is probably accidentally left there when I have tried the effect of the adjustment in this case.
So should be

rcov <- getResidualCov<https://jenniniku.github.io/gllvm/reference/getResidualCov.gllvm.html>(fit_env)
rcov0 <- getResidualCov<https://jenniniku.github.io/gllvm/reference/getResidualCov.gllvm.html>(fit3lv)

when default adjustment is used.

Best wishes,
Jenni
________________________________
Lähettäjä: Kevin <notifications@github.com>
Lähetetty: sunnuntai 6. joulukuuta 2020 23.51
Vastaanottaja: JenniNiku/gllvm <gllvm@noreply.github.com>
Kopio: Niku, Jenni <jenni.m.e.niku@jyu.fi>; Mention <mention@noreply.github.com>
Aihe: [JenniNiku/gllvm] Calculation of explained variation for negative binomial model (#25)


Hello @JenniNiku<https://github.com/JenniNiku> , in your vignette1 document<https://cran.r-project.org/web/packages/gllvm/vignettes/vignette1.html>, you provide an example on how to calculate the variation explained by the environmental variables with the ratio of the traces from the residual covariance matrices of the null and environmental models:

rcov <- getResidualCov(fit_env, adjust = 0)
rcov0 <- getResidualCov(fit3lv, adjust = 0)
rcov0$trace; rcov$trace
#> [1] 71.63626
#> [1] 53.42926
1 - rcov$trace / rcov0$trace
#> [1] 0.254159


In your example, the fitted models have negative binomial distributed responses. Why is the adjust argument set then to 0 in this case? From the documentation I read adjust should be 1 or 2 for negative binomial. Or is it not necessary in this application?

Thanks a lot,
Kevin

**Comment by KwnLi** [comment]
Thanks a lot for your help!
