### ISSUE TITLE
Can't plot model fit when using an offset

### ISSUE THREAD

**Issue by adhamab** [JenniNiku/gllvm#32]
Hi there,

I can't plot gllvm model fit with an offset for plot size (log(area)).

I just get the error message:

Error in matrix(object$params$beta0, n, p, byrow = TRUE) + offset : 
  non-conformable arrays

I can plot model fit fine without the offset, or using densities (which are not ideal).
Could you please recommend a solution?

**Comment by BertvanderVeen** [comment]
Hello! I'm afraid I can't reproduce your error. Can you provide the code you use to construct the offset matrix? The offset needs to be of the same dimension as the data matrix, y.

**Comment by adhamab** [comment]
Thanks!

species<- df %>% select(3:25)
area<-df %>% select(2)

##includeoffset
area<-log(area)
area<-as.matrix(area)

y<-as.matrix(species)

mod1<-gllvm(y, family="poisson", offset= area)

**Comment by BertvanderVeen** [comment]
OK, unfortunately that doesn't help as I don't have access to your data! Have you double checked that the dimensions of `y` and `offset` are the same? I.e. `dim(y)==dim(area)`

**Comment by adhamab** [comment]
> dim(y)
[1] 32 18
> dim(area)
[1] 32  1

**Comment by BertvanderVeen** [comment]
So that's where your issue is. The dimensions of both matrices need to be the same, so I am afraid you haven't specified the offset correctly: it has too few columns (1 versus 18).

**Comment by adhamab** [comment]
aaah right, thank you! so the offset should be repeated for each species (columns in y matrix)?

**Comment by BertvanderVeen** [comment]
Yes, if it's a site-specific property I suppose it can be the same for all species.

**Comment by adhamab** [comment]
brilliant, thanks for your help, works fine now.
