### ISSUE TITLE
Ordinal model without latent variables

### ISSUE THREAD

**Issue by BertvanderVeen** [JenniNiku/gllvm#38]
Currently, when the number of latent variables in the model is set to zero, and TMB = TRUE, estimation is handled using the branch for the laplace approximation. However, this branch does not have the option for the ordinal model (this is in the VA branch), and the VA branch cannot be used when the number of latent variables in the model is zero. 

Similarly, the gllvm.VA function is only implemented for species-specific cut-offs, though it can handle the absence of latent variables. 

As a result, a model with species-common cut-offs, and no latent variables, cannot be fit. Preferably, this would be handled using TMB and the VA branch in the future.

**Comment by JenniNiku** [comment]
This is fixed now.
