### ISSUE TITLE
Number of observations reported by logLik and used in IC calculations

### ISSUE THREAD

**Issue by stouffer** [JenniNiku/gllvm#50]
Shouldn't the number of observations that gets reported by `logLik(model)` or gets used in `AICc(model)` or `BIC(model)` be the product of the number of rows and the number of columns of `model$y`?

Currently, the `nobs` function in [aicc.gllvm.R](https://github.com/JenniNiku/gllvm/blob/master/R/aicc.gllvm.R) returns this product but other functions including `inf.criteria` in [gllvm.auxiliary.R](https://github.com/JenniNiku/gllvm/blob/master/R/gllvm.auxiliary.R) and `logLik` in [logLik.gllvm.R](https://github.com/JenniNiku/gllvm/blob/master/R/logLik.gllvm.R) only use the number of rows.

**Comment by BertvanderVeen** [comment]
Indeed. I have corrected this some time back when I implemented AICc, yet forgot to address the same issue in BIC and logLik, apparently. Thanks for noting this, it has now been addressed in my PR.
