### ISSUE TITLE
Result interpretation in vignette6

### ISSUE THREAD

**Issue by hilmanamin** [JenniNiku/gllvm#56]
Hi.. vignettte6 gives an interesting study about predictor variables to multivariate community data. how we can interpret the result in `summary(CGLLVM)`? some coefficient estimates give negative values and some are positive, for example, soil.dry(LV2)        1.5032 and fallen.leaves(LV1)  -0.6957. Is it can be concluded that most spider species prefer in more dry soil and they did not prefer in many fallen leaves habitats?

Thanks.

**Comment by BertvanderVeen** [comment]
Unlike in classical constrained ordination methods, the algorithm used here is sensitive to the initial values. In case you know non-metric multidimensional scaling, think of it like that: you will have to re-run the analysis to find an optimal solution. 

Jenni has written a paper on this, but there are some instructions in the vignettes and help pages too. Once you have found an optimal solution (use e.g. the `n.init` argument), the seed is stored in `model$seed` so you can reproduce your model, without having to re-run it multiple times frequently.

You can add a legend to your ordination plot by using the `legend` function in for base R plotting.

**Comment by BertvanderVeen** [comment]
Details on the method are available in our preprint: https://t.co/XgW6qTR81w?amp=1.

**Comment by hilmanamin** [comment]
Great. thanks for sharing the preprint and explanations.
