### ISSUE TITLE
residual plots change without re-running the model

### ISSUE THREAD

**Issue by PageG** [JenniNiku/gllvm#63]
Hello,

When I fit a model and then check the residual plots, each time I run the 'plot' command, the residual plots change. I've included two images showing an example of the change when running 'plot' twice on the same model. As you can see, in one plot the residuals look good, in the other they look less good. What's going on here?

![gllvm_residuals_1](https://user-images.githubusercontent.com/16804907/153981254-3dbc3715-c6fa-4115-b093-e3ca45bf62c9.png)
![gllvm_residuals_2](https://user-images.githubusercontent.com/16804907/153981262-7fb6825b-df50-4359-8465-9600379243db.png)

**Comment by BertvanderVeen** [comment]
Thanks for your question! The residuals used in gllvm are randomized quantile residuals, which include a random component (see? residuals for some information) . As such, they will always look different from plot to plot, unless you set a seed.

You can of course use a seed to ensure reproducibility of a plot.

**Comment by PageG** [comment]
OK, good to know. Many thanks.
